/* USERS */

CREATE TABLE IF NOT EXISTS t_users (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	name	VARCHAR(30) NOT NULL,
	surname	VARCHAR(20),
	email	VARCHAR(30) NULL DEFAULT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* ACL tables */

CREATE TABLE IF NOT EXISTS t_acl_actions (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	code	VARCHAR(40) NOT NULL,
	label	VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	UNIQUE KEY uk_t_acl_actions (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_acl_filters (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	code	VARCHAR(40) NOT NULL,
	label	VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	UNIQUE KEY uk_t_acl_filters (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_acl_roles (
	id		INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	code	VARCHAR(40) NOT NULL,
	label	VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	UNIQUE KEY uk_t_acl_roles (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS acl (
	type			ENUM('URL', 'OBJECT', 'ORM') NOT NULL,
	target			VARCHAR(100) NOT NULL,
	method			VARCHAR(40) NULL DEFAULT NULL,
	role			INTEGER UNSIGNED NULL DEFAULT NULL,
	action			INTEGER UNSIGNED NULL DEFAULT NULL,
	filter			INTEGER UNSIGNED NULL DEFAULT NULL,
	filter_query	VARCHAR(1024) NULL DEFAULT NULL,
	UNIQUE KEY uk_t_acl (type, target, method),
	CONSTRAINT fk_t_acl__role FOREIGN KEY (role) REFERENCES t_acl_roles (id),
	CONSTRAINT fk_t_acl__action FOREIGN KEY (action) REFERENCES t_acl_actions (id),
	CONSTRAINT fk_t_acl__filter FOREIGN KEY (filter) REFERENCES t_acl_filters (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS t_acl_maps (
    type			ENUM('USER_ROLE','USER_ACTION','USER_FILTER','ROLE_ACTION','ROLE_FILTER') NOT NULL,
	user			INTEGER UNSIGNED NULL DEFAULT NULL,
	role			INTEGER UNSIGNED NULL DEFAULT NULL,
	action			INTEGER UNSIGNED NULL DEFAULT NULL,
	filter			INTEGER UNSIGNED NULL DEFAULT NULL,
	filter_value	VARCHAR(1024) NULL DEFAULT NULL,
	PRIMARY KEY (user, role, action, filter),
	CONSTRAINT fk_t_acl_maps__user FOREIGN KEY (user) REFERENCES t_users (id) ON DELETE CASCADE,
	CONSTRAINT fk_t_acl_maps__role FOREIGN KEY (role) REFERENCES t_acl_roles (id) ON DELETE CASCADE,
	CONSTRAINT fk_t_acl_maps__action FOREIGN KEY (action) REFERENCES t_acl_actions (id) ON DELETE CASCADE,
	CONSTRAINT fk_t_acl_maps__filter FOREIGN KEY (filter) REFERENCES t_acl_filters (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
